import React from 'react';
import { PageView } from '../components/Navbar';

interface Props {
  setCurrentPage?: (page: PageView) => void;
}

export const TermsPage: React.FC<Props> = ({ setCurrentPage }) => {
  return (
    <div style={{ maxWidth: '820px', margin: '0 auto', padding: '1rem 0 3rem' }}>
      <div style={{ marginBottom: '2rem', borderBottom: '1px solid var(--border-default)', paddingBottom: '1.5rem' }}>
        <span className="badge badge-neutral" style={{ marginBottom: '0.75rem' }}>LEGAL & GOVERNANCE</span>
        <h1 style={{ fontSize: '2.2rem', fontWeight: 800, color: 'var(--text-primary)', letterSpacing: '-0.02em', lineHeight: 1.2 }}>
          Terms of Scientific Service & Research Usage
        </h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginTop: '0.5rem' }}>
          Effective Date: October 2026 | Version 1.0.4 | GoNax Research & Production Standards
        </p>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem', fontSize: '0.95rem', lineHeight: 1.7, color: 'var(--text-primary)' }}>
        <section>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '0.75rem', color: 'var(--text-primary)' }}>
            1. Scientific Scope & Purpose
          </h2>
          <p style={{ marginBottom: '0.75rem' }}>
            GoNax is a scientific intelligence platform engineered to provide species-specific allometric modeling, biomass estimation, and carbon stock calculations. The calculations provided are based on peer-reviewed mathematical literature, empirical forestry datasets, and calibrated allometric regressions.
          </p>
          <p>
            Users are advised that biological variability, micro-climates, soil conditions, and forest stand density introduce inherent uncertainty. Model outputs must be evaluated alongside the accompanying confidence metrics, calibration intervals, and extrapolation flags.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '0.75rem', color: 'var(--text-primary)' }}>
            2. Carbon Credit & MRV Compliance Advisory
          </h2>
          <p style={{ marginBottom: '0.75rem' }}>
            Estimates generated by GoNax provide scientific evidence for carbon accounting frameworks (e.g., IPCC Good Practice Guidance, VCS/Verra, Gold Standard). However, final crediting requires adherence to regional methodology standards, field sample validation, and independent auditor verification.
          </p>
          <p>
            GoNax disclaims liability for financial losses arising from regulatory disputes or trading decisions executed without independent ground-truth inventory certification.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '0.75rem', color: 'var(--text-primary)' }}>
            3. Algorithmic Integrity & Citation Requirements
          </h2>
          <p style={{ marginBottom: '0.75rem' }}>
            Publications, reports, and public disclosures utilizing GoNax estimations must maintain citation integrity by referencing the specific model IDs, authors, and DOIs provided in the calculation provenance payload.
          </p>
          <p>
            Reverse engineering, automated scraping, or submitting falsified calibration inputs designed to bypass extrapolation guardrails is strictly prohibited.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '0.75rem', color: 'var(--text-primary)' }}>
            4. Warranty & Scientific Limitations
          </h2>
          <p>
            The software, data models, and analytical tools are provided "as-is" under rigorous academic standards. While GoNax validates every equation against published literature benchmarks, no warranty of absolute biological exactitude is implied for individual specimen outliers.
          </p>
        </section>

        {setCurrentPage && (
          <div style={{ marginTop: '1.5rem', paddingTop: '1.5rem', borderTop: '1px solid var(--border-default)' }}>
            <button className="btn-secondary" onClick={() => setCurrentPage('dashboard')}>
              Return to Workspace
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
